### ISSUE TITLE
Download SNPE model: Name or service not know

### ISSUE THREAD

**Issue by ysh329** [XiaoMi/mobile-ai-bench#13]
🙇 

ERROR logs as below:
```shell
root@cross-compile:/opt/mobile-ai-bench# python ./tools/benchmark.py --frameworks=SNPE                     [83/99]
Prepare to run models on armeabi-v7a
* Build //aibench/benchmark:model_benchmark with ABI armeabi-v7a
/system/lib/libcdsprpc.so does not exists! Skip DSP.
INFO: Analysed target //aibench/benchmark:model_benchmark (17 packages loaded).
INFO: Found 1 target...
Target //aibench/benchmark:model_benchmark up-to-date:
  bazel-bin/aibench/benchmark/model_benchmark
INFO: Elapsed time: 9.494s, Critical Path: 0.71s
INFO: 3 processes, local.
INFO: Build completed successfully, 5 total actions
Build done!

=====================================================================
Trying to lock device ac516aca
Run on device: ac516aca, sdm660, Mi Note 3
Adjust power to performance mode on ac516aca, sdm660
adbd is already running as root
remount of /system failed: Read-only file system
remount failed
/system/bin/sh: can't create /sys/class/devfreq/1d84000.ufshc/governor: No such file or directory
/system/bin/sh: can't create /sys/class/devfreq/aa00000.qcom,vidc:arm9_bus_ddr/governor: No such file or directory
/system/bin/sh: can't create /sys/class/devfreq/aa00000.qcom,vidc:bus_cnoc/governor: No such file or directory
/system/bin/sh: can't create /sys/class/devfreq/aa00000.qcom,vidc:venus_bus_ddr/governor: No such file or director
y
/system/bin/sh: can't create /sys/class/devfreq/aa00000.qcom,vidc:venus_bus_llcc/governor: No such file or directory
bsnpe_dsp_skel.so                                                                                          [27/99]
Equal checksum with bazel-mobile-ai-bench/external/snpe/lib/dsp/libsnpe_dsp_domains_skel.so and /data/local/tmp/ai
bench/libsnpe_dsp_domains_skel.so
Equal checksum with bazel-mobile-ai-bench/external/snpe/lib/arm-android-gcc4.9/libSNPE_G.so and /data/local/tmp/ai
bench/libSNPE_G.so
Equal checksum with bazel-mobile-ai-bench/external/snpe/lib/arm-android-gcc4.9/libsymphony-cpu.so and /data/local/
tmp/aibench/libsymphony-cpu.so
Equal checksum with bazel-mobile-ai-bench/external/snpe/lib/arm-android-gcc4.9/libSNPE.so and /data/local/tmp/aibe
nch/libSNPE.so
Equal checksum with bazel-mobile-ai-bench/external/snpe/lib/arm-android-gcc4.9/libsymphonypower.so and /data/local
/tmp/aibench/libsymphonypower.so
Equal checksum with bazel-mobile-ai-bench/external/snpe/lib/arm-android-gcc4.9/libsnpe_dsp_domains.so and /data/lo
cal/tmp/aibench/libsnpe_dsp_domains.so
Equal checksum with bazel-mobile-ai-bench/external/snpe/lib/arm-android-gcc4.9/libsnpe_adsp.so and /data/local/tmp
/aibench/libsnpe_adsp.so
Equal checksum with /opt/android-ndk-r15c/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/libgnustl_shared.so a
nd /data/local/tmp/aibench/libgnustl_shared.so
Equal checksum with /opt/android-ndk-r15c/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/libgnustl_shared.so a
nd /data/local/tmp/aibench/libgnustl_shared.so
downloading inception_v3_quantized.dlc...
Traceback (most recent call last):
  File "./tools/benchmark.py", line 225, in <module>
    main(unused_args=[sys.argv[0]] + unparsed)
  File "./tools/benchmark.py", line 217, in main
    frameworks, model_names, runtimes, output_dir=FLAGS.output_dir)
  File "/opt/mobile-ai-bench/tools/sh_commands.py", line 340, in adb_run
    output_dir, frameworks, build_mace)
  File "/opt/mobile-ai-bench/tools/sh_commands.py", line 288, in prepare_all_model_and_input
    device_bin_path, output_dir)
  File "/opt/mobile-ai-bench/tools/sh_commands.py", line 264, in prepare_model_and_input
    download_file(models_inputs, file_name, output_dir)
  File "/opt/mobile-ai-bench/tools/sh_commands.py", line 156, in download_file
    urllib.urlretrieve(url, file_path)
  File "/usr/lib/python2.7/urllib.py", line 98, in urlretrieve
    return opener.retrieve(url, filename, reporthook, data)
  File "/usr/lib/python2.7/urllib.py", line 245, in retrieve
    fp = self.open(url, data)
  File "/usr/lib/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/usr/lib/python2.7/urllib.py", line 443, in open_https
    h.endheaders(data)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1270, in connect
    HTTPConnection.connect(self)
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
IOError: [Errno socket error] [Errno -2] Name or service not known
```

**Comment by llhe** [comment]
@ysh329 The previous links were broken. They are fixed now and you can pull the latest code to have a try.

**Comment by ysh329** [comment]
@llhe Thanks! bother you again 👍 😆
