### ISSUE TITLE
IOError: [Errno socket error] [Errno 0] Error

### ISSUE THREAD

**Issue by liupengkd** [XiaoMi/mobile-ai-bench#32]
Configure the environment on x86 linux, then connect the computer data cable to the arm andriod device to run "bash tools/benchmark.sh --benchmark_option=Performance --target_abis=armeabi-v7a,arm64-v8a,aarch64,armhf", error "IOError: [Errno socket error] [Errno 0] Error"
INFO: Analysed target //aibench/python:benchmark (0 packages loaded).
INFO: Found 1 target...
Target //aibench/python:benchmark up-to-date:
  bazel-bin/aibench/python/benchmark
INFO: Elapsed time: 0.289s, Critical Path: 0.00s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
downloading mobilenet-v1_1544063874.pb...
Traceback (most recent call last):
  File "/home/liupeng/mobile-ai-bench-master/bazel-bin/aibench/python/benchmark.runfiles/aibench/aibench/python/benchmark.py", line 299, in <module>
    main(unused_args=[sys.argv[0]] + unparsed)
  File "/home/liupeng/mobile-ai-bench-master/bazel-bin/aibench/python/benchmark.runfiles/aibench/aibench/python/benchmark.py", line 252, in main
    FLAGS.output_dir)
  File "/home/liupeng/mobile-ai-bench-master/aibench/python/sh_commands.py", line 368, in prepare_all_models
    get_model(model, output_dir, push_list)
  File "/home/liupeng/mobile-ai-bench-master/aibench/python/sh_commands.py", line 306, in get_model
    output_dir, push_list)
  File "/home/liupeng/mobile-ai-bench-master/aibench/python/sh_commands.py", line 293, in get_model_file
    urllib.urlretrieve(file_path, local_file_path)
  File "/usr/lib/python2.7/urllib.py", line 98, in urlretrieve
    return opener.retrieve(url, filename, reporthook, data)
  File "/usr/lib/python2.7/urllib.py", line 245, in retrieve
    fp = self.open(url, data)
  File "/usr/lib/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/usr/lib/python2.7/urllib.py", line 443, in open_https
    h.endheaders(data)
  File "/usr/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 844, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1263, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python2.7/ssl.py", line 369, in wrap_socket
    _context=self)
  File "/usr/lib/python2.7/ssl.py", line 617, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 846, in do_handshake
    self._sslobj.do_handshake()
IOError: [Errno socket error] [Errno 0] Error

**Comment by lee-bin** [comment]
It seems like a network issue, so you can try something below to check it.
* use `urllib.urlretrieve` in python code to download a file.

or

* use `wget` in command line to download a file.

You can select a url from [here](https://github.com/XiaoMi/mobile-ai-bench/blob/master/aibench/proto/benchmark.meta) to test.
